import assert from "node:assert/strict";
import test from "node:test";
import type { Message } from "@earendil-works/pi-ai";
import { completeHandoffPrompt } from "../../extensions/handoff-generation.ts";

test("routes a custom API model through the active model registry", async () => {
	const model = {
		provider: "custom-bridge",
		id: "custom-model",
		api: "custom-stream-api",
	};
	const signal = new AbortController().signal;
	const userMessage: Message = {
		role: "user",
		content: [{ type: "text", text: "handoff context" }],
		timestamp: 1,
	};
	let receivedOptions: Record<string, unknown> | undefined;
	const ctx = {
		model,
		modelRegistry: {
			async complete(receivedModel: unknown, request: any, options: Record<string, unknown>) {
				assert.equal(receivedModel, model);
				assert.match(request.systemPrompt, /context transfer assistant/);
				assert.equal(request.messages[0], userMessage);
				receivedOptions = options;
				return {
					stopReason: "stop",
					content: [{ type: "text", text: "generated by custom provider" }],
				};
			},
		},
	} as any;

	const result = await completeHandoffPrompt(ctx, userMessage, signal, "handoff-session");

	assert.equal(result, "generated by custom provider");
	assert.equal(receivedOptions?.signal, signal);
	assert.equal(receivedOptions?.cacheRetention, "none");
	assert.equal(receivedOptions?.sessionId, "handoff-session");
});

test("returns null when the model registry reports an aborted response", async () => {
	const message: Message = {
		role: "user",
		content: [{ type: "text", text: "handoff context" }],
		timestamp: 1,
	};
	const ctx = {
		model: { provider: "custom-bridge", id: "custom-model", api: "custom-stream-api" },
		modelRegistry: {
			async complete() {
				return { stopReason: "aborted", content: [] };
			},
		},
	} as any;

	const result = await completeHandoffPrompt(
		ctx,
		message,
		new AbortController().signal,
		"handoff-session",
	);

	assert.equal(result, null);
});

const completionUserMessage = {
	role: "user",
	content: [{ type: "text", text: "handoff context" }],
	timestamp: 1,
} as any;

function completionContext(response: Record<string, unknown>) {
	return {
		model: { provider: "custom-bridge", id: "custom-model", api: "custom-stream-api" },
		modelRegistry: {
			async complete() {
				return response;
			},
		},
	} as any;
}

test("throws the provider error message when completion stops with an error", async () => {
	await assert.rejects(
		completeHandoffPrompt(
			completionContext({
				stopReason: "error",
				content: [],
				errorMessage: "Claude session reconstruction failed",
			}),
			completionUserMessage,
			new AbortController().signal,
			"handoff-session",
		),
		/Claude session reconstruction failed/,
	);
});

test("rejects a truncated handoff prompt", async () => {
	await assert.rejects(
		completeHandoffPrompt(
			completionContext({
				stopReason: "length",
				content: [{ type: "text", text: "partial prompt" }],
			}),
			completionUserMessage,
			new AbortController().signal,
			"handoff-session",
		),
		/truncated/i,
	);
});

for (const [name, content] of [
	["no text blocks", []],
	["whitespace-only text", [{ type: "text", text: "  \n" }]],
] as const) {
	test(`rejects successful handoff output with ${name}`, async () => {
		await assert.rejects(
			completeHandoffPrompt(
				completionContext({ stopReason: "stop", content }),
				completionUserMessage,
				new AbortController().signal,
				"handoff-session",
			),
			/empty prompt/i,
		);
	});
}

test("rejects an incomplete nonterminal stop reason", async () => {
	await assert.rejects(
		completeHandoffPrompt(
			completionContext({ stopReason: "toolUse", content: [] }),
			completionUserMessage,
			new AbortController().signal,
			"handoff-session",
		),
		/incomplete/i,
	);
});

test("assembles the handoff request and returns registry text", async () => {
	const generation = await import("../../extensions/handoff-generation.ts");
	assert.equal(typeof (generation as any).generateHandoffPrompt, "function");

	const model = { provider: "custom-bridge", id: "custom-model", api: "custom-stream-api" };
	let receivedRequest: any;
	const ctx = {
		model,
		modelRegistry: {
			async complete(_model: unknown, request: unknown) {
				receivedRequest = request;
				return {
					stopReason: "stop",
					content: [{ type: "text", text: "focused handoff" }],
				};
			},
		},
		ui: {
			custom(factory: Function) {
				return new Promise((resolve) => {
					factory({}, {}, {}, resolve);
				});
			},
		},
	} as any;
	class FakeLoader {
		readonly signal = new AbortController().signal;
		onAbort?: () => void;
	}
	const runtime = {
		uuidv7: () => "handoff-session",
		BorderedLoader: FakeLoader,
		convertToLlm: (messages: unknown[]) => messages,
		serializeConversation: () => "serialized conversation",
	} as any;

	const result = await (generation as any).generateHandoffPrompt(
		{
			ctx,
			messages: [{ role: "user", content: "current task", timestamp: 1 }],
			goal: "continue in a fresh session",
		},
		async () => runtime,
	);

	assert.equal(result, "focused handoff");
	assert.equal(receivedRequest.messages[0].content[0].text, [
		"## Conversation History",
		"",
		"serialized conversation",
		"",
		"## User's Goal for New Thread",
		"",
		"continue in a fresh session",
	].join("\n"));
});

test("propagates generation failures after the loader closes", async () => {
	const generation = await import("../../extensions/handoff-generation.ts");
	assert.equal(typeof (generation as any).generateHandoffPrompt, "function");

	const ctx = {
		model: { provider: "custom-bridge", id: "custom-model", api: "custom-stream-api" },
		modelRegistry: {
			async complete() {
				throw new Error("provider failed");
			},
		},
		ui: {
			custom(factory: Function) {
				return new Promise((resolve) => {
					factory({}, {}, {}, resolve);
				});
			},
		},
	} as any;
	class FakeLoader {
		readonly signal = new AbortController().signal;
		onAbort?: () => void;
	}
	const runtime = {
		uuidv7: () => "handoff-session",
		BorderedLoader: FakeLoader,
		convertToLlm: (messages: unknown[]) => messages,
		serializeConversation: () => "serialized conversation",
	} as any;

	await assert.rejects(
		(generation as any).generateHandoffPrompt(
			{
				ctx,
				messages: [{ role: "user", content: "current task", timestamp: 1 }],
				goal: "continue in a fresh session",
			},
			async () => runtime,
		),
		/provider failed/,
	);
});
