import assert from "node:assert/strict";
import test from "node:test";
import type { Message } from "@earendil-works/pi-ai";
import {
	completeHandoffPrompt,
	generateHandoffPrompt,
} from "../../extensions/handoff-generation.ts";

test("routes a custom API model through the active model registry", async () => {
	const model = {
		provider: "custom-bridge",
		id: "custom-model",
		api: "custom-stream-api",
	};
	const signal = new AbortController().signal;
	const userMessage: Message = {
		role: "user",
		content: [{ type: "text", text: "handoff context" }],
		timestamp: 1,
	};
	let receivedOptions: Record<string, unknown> | undefined;
	const ctx = {
		model,
		modelRegistry: {
			async complete(receivedModel: unknown, request: any, options: Record<string, unknown>) {
				assert.equal(receivedModel, model);
				assert.equal(request.messages[0], userMessage);
				receivedOptions = options;
				return {
					stopReason: "stop",
					content: [{
						type: "text",
						text: "HANDOFF_ACTION: CONTINUE\n\ngenerated by custom provider",
					}],
				};
			},
		},
	} as any;

	const result = await completeHandoffPrompt(ctx, userMessage, signal, "handoff-session");

	assert.deepEqual(result, { action: "continue", prompt: "generated by custom provider" });
	assert.equal(receivedOptions?.signal, signal);
	assert.equal(receivedOptions?.cacheRetention, "none");
	assert.equal(receivedOptions?.sessionId, "handoff-session");
});

test("returns null when the model registry reports an aborted response", async () => {
	const message: Message = {
		role: "user",
		content: [{ type: "text", text: "handoff context" }],
		timestamp: 1,
	};
	const ctx = {
		model: { provider: "custom-bridge", id: "custom-model", api: "custom-stream-api" },
		modelRegistry: {
			async complete() {
				return { stopReason: "aborted", content: [] };
			},
		},
	} as any;

	const result = await completeHandoffPrompt(
		ctx,
		message,
		new AbortController().signal,
		"handoff-session",
	);

	assert.equal(result, null);
});

const completionUserMessage = {
	role: "user",
	content: [{ type: "text", text: "handoff context" }],
	timestamp: 1,
} as any;

function completionContext(response: Record<string, unknown>) {
	return {
		model: { provider: "custom-bridge", id: "custom-model", api: "custom-stream-api" },
		modelRegistry: {
			async complete() {
				return response;
			},
		},
	} as any;
}

test("throws the provider error message when completion stops with an error", async () => {
	await assert.rejects(
		completeHandoffPrompt(
			completionContext({
				stopReason: "error",
				content: [],
				errorMessage: "Claude session reconstruction failed",
			}),
			completionUserMessage,
			new AbortController().signal,
			"handoff-session",
		),
		/Claude session reconstruction failed/,
	);
});

test("rejects a truncated handoff prompt", async () => {
	await assert.rejects(
		completeHandoffPrompt(
			completionContext({
				stopReason: "length",
				content: [{ type: "text", text: "partial prompt" }],
			}),
			completionUserMessage,
			new AbortController().signal,
			"handoff-session",
		),
		/truncated/i,
	);
});

for (const [name, content] of [
	["no text blocks", []],
	["whitespace-only text", [{ type: "text", text: "  \n" }]],
] as const) {
	test(`rejects successful handoff output with ${name}`, async () => {
		await assert.rejects(
			completeHandoffPrompt(
				completionContext({ stopReason: "stop", content }),
				completionUserMessage,
				new AbortController().signal,
				"handoff-session",
			),
			/empty prompt/i,
		);
	});
}

test("rejects an incomplete nonterminal stop reason", async () => {
	await assert.rejects(
		completeHandoffPrompt(
			completionContext({ stopReason: "toolUse", content: [] }),
			completionUserMessage,
			new AbortController().signal,
			"handoff-session",
		),
		/incomplete/i,
	);
});

for (const [label, marker, action] of [
	["continuing", "CONTINUE", "continue"],
	["recommendation offer", "OFFER", "offer"],
	["waiting", "WAIT", "wait"],
] as const) {
	test(`parses a ${label} handoff action separately from its prompt`, async () => {
		const result = await completeHandoffPrompt(
			completionContext({
				stopReason: "stop",
				content: [{ type: "text", text: `HANDOFF_ACTION: ${marker}\n\n## Context\nCheckpoint` }],
			}),
			completionUserMessage,
			new AbortController().signal,
			"handoff-session",
		);

		assert.deepEqual(result, { action, prompt: "## Context\nCheckpoint" });
	});
}

for (const [name, text] of [
	["a missing action", "## Context\nCheckpoint"],
	["an unknown action", "HANDOFF_ACTION: REVIEW\n\n## Context\nCheckpoint"],
	["an empty prompt", "HANDOFF_ACTION: WAIT\n\n  "],
] as const) {
	test(`rejects successful handoff output with ${name}`, async () => {
		await assert.rejects(
			completeHandoffPrompt(
				completionContext({ stopReason: "stop", content: [{ type: "text", text }] }),
				completionUserMessage,
				new AbortController().signal,
				"handoff-session",
			),
			/invalid action|empty prompt/i,
		);
	});
}

for (const [marker, replayLastAnswer] of [["YES", true], ["NO", false]] as const) {
	test(`parses ${marker} answer replay without leaking the control into the prompt`, async () => {
		const result = await completeHandoffPrompt(
			completionContext({
				stopReason: "stop",
				content: [{ type: "text", text: `HANDOFF_ACTION: WAIT\r\nHANDOFF_REPLAY_LAST_ANSWER: ${marker}\r\n\r\n## Context\r\nCheckpoint` }],
			}),
			completionUserMessage,
			new AbortController().signal,
			"handoff-session",
		);
		assert.deepEqual(result, { action: "wait", replayLastAnswer, prompt: "## Context\nCheckpoint" });
	});
}

for (const controls of [
	"HANDOFF_REPLAY_LAST_ANSWER: MAYBE",
	"HANDOFF_REPLAY_LAST_ANSWER: yes",
	"HANDOFF_REPLAY_LAST_ANSWER YES",
	"HANDOFF_REPLAY_LAST_ANSWER: YES\n\nHANDOFF_REPLAY_LAST_ANSWER: NO",
	"HANDOFF_REPLAY_LAST_ANSWER: YES\nHANDOFF_REPLAY_LAST_ANSWER: YES",
	"HANDOFF_REPLAY_LAST_ANSWER: YES\n\n## Context\nCheckpoint\nHANDOFF_REPLAY_LAST_ANSWER: NO",
	"## Context\nCheckpoint\nHANDOFF_REPLAY_LAST_ANSWER: YES",
]) {
	test(`rejects malformed or duplicate replay controls: ${controls.replaceAll("\n", " / ")}`, async () => {
		await assert.rejects(completeHandoffPrompt(
			completionContext({
				stopReason: "stop",
				content: [{ type: "text", text: `HANDOFF_ACTION: WAIT\n${controls}\n\nCheckpoint` }],
			}),
			completionUserMessage,
			new AbortController().signal,
			"handoff-session",
		), /invalid.*replay/i);
	});
}

test("a replay control without checkpoint text is still an empty handoff", async () => {
	await assert.rejects(completeHandoffPrompt(
		completionContext({
			stopReason: "stop",
			content: [{ type: "text", text: "HANDOFF_ACTION: WAIT\nHANDOFF_REPLAY_LAST_ANSWER: YES\n\n" }],
		}),
		completionUserMessage,
		new AbortController().signal,
		"handoff-session",
	), /empty prompt/i);
});

test("distinguishes current and legacy manual goals from automatic rollover policy", async () => {
	const generation = await import("../../extensions/handoff-generation.ts");
	assert.equal(typeof (generation as any).generateHandoffPrompt, "function");

	const model = { provider: "custom-bridge", id: "custom-model", api: "custom-stream-api" };
	const receivedRequests: any[] = [];
	const ctx = {
		model,
		modelRegistry: {
			async complete(_model: unknown, request: unknown) {
				receivedRequests.push(request);
				return {
					stopReason: "stop",
					content: [{ type: "text", text: "HANDOFF_ACTION: CONTINUE\n\nfocused handoff" }],
				};
			},
		},
		ui: {
			custom(factory: Function) {
				return new Promise((resolve) => {
					factory({}, {}, {}, resolve);
				});
			},
		},
	} as any;
	class FakeLoader {
		readonly signal = new AbortController().signal;
		onAbort?: () => void;
	}
	const runtime = {
		uuidv7: () => "handoff-session",
		BorderedLoader: FakeLoader,
		convertToLlm: (messages: unknown[]) => messages,
		serializeConversation: (messages: Array<{ content?: string }>) =>
			messages.map((message) => message.content).join(" | "),
	} as any;

	const manualResult = await (generation as any).generateHandoffPrompt(
		{
			ctx,
			messages: [{ role: "user", content: "current task", timestamp: 1 }],
			intent: { kind: "manual", goal: "review the completed work" },
			goal: "stale legacy goal",
		},
		async () => runtime,
	);
	const automaticResult = await (generation as any).generateHandoffPrompt(
		{
			ctx,
			messages: [{ role: "user", content: "current task", timestamp: 1 }],
			preparationMessages: [{
				role: "assistant",
				content: "Updated TODO-a1b2c3d4",
				timestamp: 2,
			}],
			intent: { kind: "automatic" },
		},
		async () => runtime,
	);
	const legacyManualResult = await generateHandoffPrompt({
		ctx,
		messages: [{ role: "user", content: "current task", timestamp: 1 }],
		goal: "review the completed work",
	}, async () => runtime) as string | null;

	assert.deepEqual(manualResult, { action: "continue", prompt: "focused handoff" });
	assert.deepEqual(automaticResult, { action: "continue", prompt: "focused handoff" });
	assert.equal(legacyManualResult?.trim(), "focused handoff");
	assert.equal(receivedRequests[0].messages[0].content[0].text, [
		"## Conversation History",
		"",
		"current task",
		"",
		"## Handoff Mode",
		"",
		"MANUAL",
		"",
		"## User's Goal for New Thread",
		"",
		"review the completed work",
	].join("\n"));
	assert.equal(receivedRequests[1].messages[0].content[0].text, [
		"## User Conversation",
		"",
		"current task",
		"",
		"## Automatic Handoff Preparation",
		"",
		"Updated TODO-a1b2c3d4",
		"",
		"## Handoff Mode",
		"",
		"AUTOMATIC",
		"",
		"No new user goal was provided. Determine continuation only from explicit unfinished user-requested work in the User Conversation.",
	].join("\n"));
	assert.equal(receivedRequests[2].messages[0].content[0].text, [
		"## Conversation History",
		"",
		"current task",
		"",
		"## Handoff Mode",
		"",
		"MANUAL",
		"",
		"## User's Goal for New Thread",
		"",
		"review the completed work",
	].join("\n"));
	assert.doesNotMatch(receivedRequests[0].systemPrompt, /Continuity Todos|HANDOFF_ACTION: OFFER/);
	assert.doesNotMatch(receivedRequests[2].systemPrompt, /Continuity Todos|HANDOFF_ACTION: OFFER/);
	assert.match(receivedRequests[1].systemPrompt, /## Continuity Todos/);
	assert.doesNotMatch(
		receivedRequests[1].systemPrompt,
		/do not appear in the user conversation, preparation transcript, or manual goal/,
	);
});

test("automatic classification receives the exact candidate and labels internal extension context", async () => {
	const answer = "  The proxy times out.\n\n```ts\ntimeout: 30\n```\n";
	const requests: any[] = [];
	const ctx: any = {
		model: { provider: "test", id: "model" },
		modelRegistry: {
			async complete(_model: unknown, request: any) {
				requests.push(request);
				return { stopReason: "stop", content: [{ type: "text", text: "HANDOFF_ACTION: WAIT\nHANDOFF_REPLAY_LAST_ANSWER: YES\n\ncheckpoint" }] };
			},
		},
		ui: { custom: (factory: Function) => new Promise((resolve) => factory({}, {}, {}, resolve)) },
	};
	const runtime: any = {
		uuidv7: () => "generation",
		BorderedLoader: class { signal = new AbortController().signal; },
		// Pi converts custom messages to user messages and discards customType.
		convertToLlm: (messages: any[]) => messages.map((message) => ({
			role: message.role === "custom" ? "user" : message.role,
			content: message.content,
		})),
		serializeConversation: JSON.stringify,
	};
	const messages: any[] = [
		{ role: "user", content: "Explain the timeout", timestamp: 1 },
		{ role: "custom", customType: "background-result", content: "Background task completed", display: true, timestamp: 2 },
		{ role: "assistant", content: [{ type: "thinking", thinking: "private reasoning" }, { type: "text", text: answer }], stopReason: "stop", timestamp: 3 },
	];
	const input = {
		ctx, messages,
		preparationMessages: [{ role: "assistant", content: [{ type: "text", text: "Updated TODO-a1b2c3d4" }], stopReason: "stop", timestamp: 4 }] as any[],
		intent: { kind: "automatic" } as const,
	};
	assert.deepEqual(await generateHandoffPrompt(input, async () => runtime), {
		action: "wait", replayLastAnswer: true, prompt: "checkpoint",
	});
	const request = requests[0].messages[0].content[0].text;
	const candidate = request.split("## Answer Replay Candidate\n\n")[1].split("\n\n##")[0];
	assert.equal(JSON.parse(candidate), answer);
	assert.ok(request.includes("[Internal extension message: background-result]"));
	assert.equal(messages[1].content, "Background task completed", "serialization must not mutate source history");

	await generateHandoffPrompt({ ...input, intent: { kind: "manual", goal: "review" } }, async () => runtime);
	assert.ok(!requests[1].messages[0].content[0].text.includes("## Answer Replay Candidate"));
});

test("fails closed for a legacy automatic call across an activation", async () => {
	let completionCalls = 0;
	const ctx = {
		model: { provider: "custom-bridge", id: "custom-model", api: "custom-stream-api" },
		modelRegistry: {
			async complete() {
				completionCalls += 1;
				return {
					stopReason: "stop",
					content: [{ type: "text", text: "HANDOFF_ACTION: WAIT\n\ncheckpoint" }],
				};
			},
		},
		ui: {
			custom(factory: Function) {
				return new Promise((resolve) => factory({}, {}, {}, resolve));
			},
		},
	} as any;
	class FakeLoader {
		readonly signal = new AbortController().signal;
		onAbort?: () => void;
	}
	const runtime = {
		uuidv7: () => "handoff-session",
		BorderedLoader: FakeLoader,
		convertToLlm: (messages: unknown[]) => messages,
		serializeConversation: () => "serialized conversation",
	} as any;

	const result = await generateHandoffPrompt({
		ctx,
		messages: [{ role: "user", content: "current task", timestamp: 1 }],
		goal: "Continue the current task in a fresh session. Preserve the current objective, decisions, progress, blockers, and concrete next steps.",
	} as any, async () => runtime) as string | null;

	if (result !== null) result.trim();
	assert.equal(result, null);
	assert.equal(completionCalls, 0);
});

test("propagates generation failures after the loader closes", async () => {
	const generation = await import("../../extensions/handoff-generation.ts");
	assert.equal(typeof (generation as any).generateHandoffPrompt, "function");

	const ctx = {
		model: { provider: "custom-bridge", id: "custom-model", api: "custom-stream-api" },
		modelRegistry: {
			async complete() {
				throw new Error("provider failed");
			},
		},
		ui: {
			custom(factory: Function) {
				return new Promise((resolve) => {
					factory({}, {}, {}, resolve);
				});
			},
		},
	} as any;
	class FakeLoader {
		readonly signal = new AbortController().signal;
		onAbort?: () => void;
	}
	const runtime = {
		uuidv7: () => "handoff-session",
		BorderedLoader: FakeLoader,
		convertToLlm: (messages: unknown[]) => messages,
		serializeConversation: () => "serialized conversation",
	} as any;

	await assert.rejects(
		(generation as any).generateHandoffPrompt(
			{
				ctx,
				messages: [{ role: "user", content: "current task", timestamp: 1 }],
				intent: { kind: "manual", goal: "continue in a fresh session" },
			},
			async () => runtime,
		),
		/provider failed/,
	);
});
